services:
    serveur_db:
        image: postgres
        ports:
            - "8432:5432"
        environment:
            - POSTGRES_PORT=8432
            - POSTGRES_DB=projectalog
            - POSTGRES_USER=alog_db
            - POSTGRES_PASSWORD=123456789
        networks:
            default:
                aliases:
                    - db.server
    service_backup:
        image: prodrigestivill/postgres-backup-local
        restart: always
        user: postgres:postgres
        volumes:
            - /var/opt/pgbackups:/backups
        links:
            - serveur_db
        environment:
            - POSTGRES_HOST=serveur_db
            - POSTGRES_DB=projectalog
            - POSTGRES_USER=alog_db
            - POSTGRES_PASSWORD=123456789
            - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --format=plain --blobs --inserts
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=6650
    services_getwaye:
        build: ./ApiGateway
        volumes:
            - ./ApiGateway:/app
            - /app/node_modules
        command: npm start
        ports:
            - "8080:8080"
        environment: 
        NODE_ENV: development
        LOG_LEVEL: debug
    payment:
        depends_on:
            - serveur_db
        build:
            context: ./Payment
            target: development
        volumes:
            - ./Payment:/src
            - /src/node_modules
        command: npm run start:dev
        environment: 
            NODE_ENV: development
            DEBUG: src:*
        networks:
        default:
            aliases:
                - payment.service